# Generated by Django 5.1 on 2024-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('register_id', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parent', models.CharField(max_length=30)),
                ('parent_no', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('teacher_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
